version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "00:00"
    reviewers:
      - 'Doist/backend'
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "00:00"
    reviewers:
      - 'Doist/backend'
    commit-message:
      prefix: "chore(deps):"
