name: Publish package to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.14"

      - name: Install project
        run: uv sync

      - name: Build and publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv build
          uv publish
